### ISSUE TITLE
Crash: assert failure: ninfo->hasOffset() in vtextdocumentlayout.cpp

### ISSUE THREAD

**Issue by htfy96** [tamlok/vnote#435]
OS Version (操作系统): Linux

VNote Version (VNote版本): 2.0

Symptoms (表现): 启用编辑模式MathJax预览，在打开特定文件、正在渲染公式时进行编辑会崩溃

How to Repro (如何复现):
1. 打开某个具有MathJax的md文件，一开始在预览模式，之后进入编辑模式，在公式没有完全渲染完的时候编辑，就会崩溃

### `bt full`
```
#0  0x00007ffff6882d7f in raise () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007ffff686d672 in abort () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x000000000048393a in ?? ()
No symbol table info available.
#3  0x00007ffff6c8bf6f in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#4  0x00007ffff6c8d826 in QMessageLogger::fatal(char const*, ...) const () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#5  0x00007ffff6c89096 in qt_assert(char const*, char const*, int) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#6  0x00000000005aeeef in ?? ()
No symbol table info available.
#7  0x00000000005af776 in ?? ()
No symbol table info available.
#8  0x00000000005b214c in ?? ()
No symbol table info available.
#9  0x00000000005a69c0 in ?? ()
No symbol table info available.
#10 0x00007ffff6e92c93 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#11 0x0000000000661252 in VMathJaxInplacePreviewHelper::inplacePreviewMathjaxBlockUpdated(QVector<QSharedPointer<VImageToPreview> > const&) ()
No symbol table info available.
#12 0x000000000062494d in ?? ()
No symbol table info available.
#13 0x0000000000625488 in ?? ()
No symbol table info available.
#14 0x00007ffff6e92c93 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#15 0x0000000000660bbb in VMathJaxPreviewHelper::mathjaxPreviewResultReady(int, int, unsigned long long, QString const&, QByteArray const&) ()
No symbol table info available.
#16 0x0000000000622376 in ?? ()
No symbol table info available.
#17 0x00007ffff6e92c93 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#18 0x0000000000660efe in VMathJaxWebDocument::mathjaxPreviewResultReady(int, int, unsigned long long, QString const&, QString const&) ()
No symbol table info available.
#19 0x00007ffff6e74395 in QMetaMethod::invoke(QObject*, Qt::ConnectionType, QGenericReturnArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument, QGenericArgument) const () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#20 0x00007ffff72fa951 in QMetaObjectPublisher::invokeMethod(QObject*, int, QJsonArray const&) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebChannel.so.5
No symbol table info available.
#21 0x00007ffff72ff1e6 in QMetaObjectPublisher::handleMessage(QJsonObject const&, QWebChannelAbstractTransport*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebChannel.so.5
No symbol table info available.
#22 0x00007ffff6e92c93 in QMetaObject::activate(QObject*, int, int, void**) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#23 0x00007ffff73057a4 in QWebChannelAbstractTransport::messageReceived(QJsonObject const&, QWebChannelAbstractTransport*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebChannel.so.5
No symbol table info available.
#24 0x00007ffff0a250a3 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#25 0x00007ffff0a25329 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#26 0x00007ffff0f562ab in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#27 0x00007ffff0e884e8 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#28 0x00007ffff0e959fe in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#29 0x00007ffff0e81c09 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#30 0x00007ffff1b8ac33 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#31 0x00007ffff1353ce3 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#32 0x00007ffff12f94e0 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#33 0x00007ffff12fb2ed in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#34 0x00007ffff12fc1e6 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#35 0x00007ffff09e5665 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5WebEngineCore.so.5
No symbol table info available.
#36 0x00007ffff6e93fb5 in QObject::event(QEvent*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#37 0x00007ffff79d28fc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#38 0x00007ffff79d99e0 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Widgets.so.5
No symbol table info available.
#39 0x00007ffff6e68fb5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#40 0x00007ffff6e6b593 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#41 0x00007ffff6ebac33 in ?? () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#42 0x00007fffee9c63cf in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#43 0x00007fffee9c7f89 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#44 0x00007fffee9c7fce in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#45 0x00007ffff6eba45c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#46 0x00007ffff6e6711b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#47 0x00007ffff6e6f8a4 in QCoreApplication::exec() () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#48 0x000000000043c3e4 in ?? ()
No symbol table info available.
#49 0x00007ffff686f223 in __libc_start_main () from /usr/lib/libc.so.6
No symbol table info available.
#50 0x00000000004832a4 in ?? ()
No symbol table info available
```

从栈上恢复出的assert msg：
```
(gdb) frame 5
#5  0x00007ffff6c89096 in qt_assert(char const*, char const*, int) () from /tmp/.mount_vnote5ULF3t/usr/bin/../lib/libQt5Core.so.5
(gdb) info frame
Stack level 5, frame at 0x7fffffffb680:
 rip = 0x7ffff6c89096; saved rip = 0x5aeeef
 called by frame at 0x7fffffffb6f0, caller of frame at 0x7fffffffb650
 Arglist at 0x7fffffffb648, args: 
 Locals at 0x7fffffffb648, Previous frame's sp is 0x7fffffffb680
 Saved registers:
  rip at 0x7fffffffb678
(gdb) x /50x 0x7fffffffb5a0
0x7fffffffb5a0:	0x0068dc2d	0x00000000	0x0068dc40	0x00000000
0x7fffffffb5b0:	0x000002f0	0x00000000	0x0000007a	0x00000000
0x7fffffffb5c0:	0x00000000	0xbff00000	0x00000000	0x40644000
0x7fffffffb5d0:	0x00000000	0x00000000	0x00000000	0x00000000
0x7fffffffb5e0:	0x00000000	0x00000000	0x00000000	0x00000000
0x7fffffffb5f0:	0xf6f6f460	0x00007fff	0x00000000	0x0000ffff
0x7fffffffb600:	0x00000000	0x40100000	0xd262ba00	0xea36177a
0x7fffffffb610:	0xffffb690	0x00007fff	0x01eb2a90	0x00000000
0x7fffffffb620:	0xffffb700	0x00007fff	0x01eb2a90	0x00000000
0x7fffffffb630:	0xffffb700	0x00007fff	0xffffb668	0x00007fff
0x7fffffffb640:	0xffffb6a0	0x00007fff	0xf6c89096	0x00007fff
0x7fffffffb650:	0x00000002	0x000002f0	0x0068dc40	0x00000000
0x7fffffffb660:	0x00000000	0x00000000
(gdb) p (char*)0x0068dc2d
$20 = 0x68dc2d "ninfo->hasOffset()"
(gdb) p (char*)0x0068dc40
$21 = 0x68dc40 "../../src/vtextdocumentlayout.cpp"
```

### config
[config.log](https://github.com/tamlok/vnote/files/2449019/config.log)

**Comment by htfy96** [comment]
Is this related to https://github.com/tamlok/vnote/commit/bc711e755cc64ba443fd0c252771e6d5152bf27e ?

**Comment by tamlok** [comment]
Yes. Please try the latest build here https://bintray.com/tamlok/vnote/vnote/_latestVersion

Thanks

**Comment by htfy96** [comment]
No crash in the latest build. Seems already fixed in https://github.com/tamlok/vnote/commit/bc711e755cc64ba443fd0c252771e6d5152bf27e
