### ISSUE TITLE
VNote-2.3-x86_64.AppImage  fedora 29 crashed

### ISSUE THREAD

**Issue by henices** [tamlok/vnote#655]
OS Version (操作系统): Linux

VNote Version: https://github.com/tamlok/vnote/releases/download/v2.3/VNote-2.3-x86_64.AppImage

Symptoms (表现):
[1]    4863 abort (core dumped)  ./VNote-latest-x86_64.AppImage

How to Repro (如何复现):

chmod a+x ./VNote-2.3-x86_64.AppImage
./VNote-2.3-x86_64.AppImage

2.2  使用正常

**Comment by tamlok** [comment]
不知道是不是换了qt 5.9.7导致的。能把appiamge解压缩了，然后直接跑app_run，看一下命令行输出什么错误吗？

谢谢！

**Comment by henices** [comment]
```
(gdb) bt
#0  0x00007ffff686853f in raise () from /lib64/libc.so.6
#1  0x00007ffff6852895 in abort () from /lib64/libc.so.6
#2  0x00000000004959f2 in ?? ()
#3  0x00007ffff6c8216f in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#4  0x00007ffff6c83a26 in QMessageLogger::fatal(char const*, ...) const () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#5  0x00007fffefcd2e80 in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5QuickWidgets.so.5
#6  0x00007fffefcd31b2 in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5QuickWidgets.so.5
#7  0x00007fffefcd5326 in QQuickWidget::resizeEvent(QResizeEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5QuickWidgets.so.5
#8  0x00007ffff7fb8d3d in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5WebEngineWidgets.so.5
#9  0x00007ffff7a0a441 in QWidget::event(QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#10 0x00007fffefcd5cbb in QQuickWidget::event(QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5QuickWidgets.so.5
#11 0x00007ffff7fb90ab in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5WebEngineWidgets.so.5
#12 0x00007ffff79cee0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff79d5ab0 in QApplication::notify(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#14 0x00007ffff6e5f7d5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#15 0x00007ffff7a034f2 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#16 0x00007ffff7a06d63 in QWidgetPrivate::show_helper() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff7a06caf in QWidgetPrivate::showChildren(bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff7a06d7f in QWidgetPrivate::show_helper() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff7a06caf in QWidgetPrivate::showChildren(bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff7a06d7f in QWidgetPrivate::show_helper() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff7a099b7 in QWidget::setVisible(bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff7a06d10 in QWidgetPrivate::showChildren(bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff7a06d7f in QWidgetPrivate::show_helper() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#24 0x00007ffff7a099b7 in QWidget::setVisible(bool) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#25 0x00007ffff79f0097 in QStackedLayout::setCurrentIndex(int) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#26 0x00007ffff79f08ea in QStackedLayout::insertWidget(int, QWidget*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff7b8a627 in QTabWidget::insertTab(int, QWidget*, QIcon const&, QString const&) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff7b8a6c4 in QTabWidget::insertTab(int, QWidget*, QString const&) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#29 0x0000000000520148 in ?? ()
#30 0x0000000000523a9e in ?? ()
#31 0x0000000000519680 in ?? ()
#32 0x0000000000519a4a in ?? ()
#33 0x00000000004a8f56 in ?? ()
#34 0x00000000004b0875 in ?? ()
#35 0x00007ffff6e96676 in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#36 0x00007ffff6e8a604 in QObject::event(QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#37 0x00007ffff79cee0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#38 0x00007ffff79d5ab0 in QApplication::notify(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Widgets.so.5
#39 0x00007ffff6e5f7d5 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#40 0x00007ffff6eb044e in QTimerInfoList::activateTimers() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#41 0x00007ffff6eb0a91 in ?? () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#42 0x00007fffeeb7706d in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#43 0x00007fffeeb77438 in ?? () from /lib64/libglib-2.0.so.0
#44 0x00007fffeeb774d0 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#45 0x00007ffff6eb0dbc in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#46 0x00007ffff6e5d92b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#47 0x00007ffff6e661a4 in QCoreApplication::exec() () from /home/henices/下载/squashfs-root/usr/bin/../lib/libQt5Core.so.5
#48 0x000000000043e270 in ?? ()
#49 0x00007ffff6854413 in __libc_start_main () from /lib64/libc.so.6
#50 0x000000000049536c in ?? ()

```

**Comment by henices** [comment]
```
[1]    28114 abort (core dumped)  ./VNote-2.3-x86_64.AppImage
[3:3:0100/000000.294261:ERROR:zygote_linux.cc(636)] Zygote could not fork: process_type renderer numfds 2 child_pid -1                                                                        
[3:3:0100/000000.294505:ERROR:zygote_linux.cc(668)] write: Broken pipe

```

**Comment by henices** [comment]
可能和系统升级未重启有关,  重启系统后问题消失, 原因未明.
